import type {Landmark,Route} from './overlay';
export const sources={neidan:'https://www.goldenelixir.com/jindan/dantian.html',chakras:'https://www.himalayanacademy.com/media/books/the-chakras_ei/web/ch16.html',tree:'https://www.chabad.org/library/article_cdo/aid/137112/jewish/Two-Systems-of-Ten-Sefirot.htm',design:'https://jovianarchive.com/pages/the-nine-centers-of-the-bodygraph-in-human-design',keys:'https://genekeys.com/how-to-read-your-profile/',iching:'https://genekeys.com/i-ching/',phases:'https://plato.stanford.edu/entries/daoism-religion/'};
export type MapLayer={id:string;name:string;note:string;points:Landmark[];routes:Route[]};
const point=(id:string,name:string,x:number,y:number,z:number,color:string,description:string,source:string,radius=.022):Landmark=>({id,name,position:[x,y,z],color,description,source,radius,kind:'Symbolic map'});
const dantian=[point('lower','下丹田 · Lower field',0,.98,.035,'#efbd64','An inner region of the lower abdomen associated with essence and cultivation in Neidan. Positions differ by lineage; this is a volume of contemplative orientation.',sources.neidan,.065),point('middle','中丹田 · Middle field',0,1.29,.035,'#69ded1','The middle field is placed in the chest region and associated with breath or qi. It is not identical to the anatomical heart.',sources.neidan,.06),point('upper','上丹田 · Upper field',0,1.595,.015,'#b3b6ff','The upper field is placed within the head and associated with spirit. The brow, crown, and upper field are shown separately.',sources.neidan,.045)];
const landmarks=[point('huiyin','會陰 · Perineum',0,.805,.005,'#e8bc83','Approximate perineal landmark used in traditional circulation maps. This is not an acupuncture locator.',sources.neidan),point('crown','百會 · Crown',0,1.704,-.015,'#d9e5ff','An approximate crown landmark, distinct from the upper field.',sources.neidan),point('sole-l','湧泉 · Left sole',.092,.03,.085,'#83c9d0','Approximate sole region, carried forward from the earlier Inner Atlas.',sources.neidan),point('sole-r','湧泉 · Right sole',-.092,.03,.085,'#83c9d0','Approximate sole region. Both feet are represented.',sources.neidan)];
const chakraNames=['Muladhara · Root','Svadhishthana · Sacral','Manipura · Navel','Anahata · Heart','Vishuddha · Throat','Ajna · Brow','Sahasrara · Crown'];
const chakraY=[.81,.96,1.1,1.29,1.44,1.6,1.76];const colors=['#ec726b','#f6a255','#e7d46b','#79cb9c','#76cfea','#a5a1ed','#e0b3ff'];
const treeNames=['Keter','Chokhmah','Binah','Chesed','Gevurah','Tiferet','Netzach','Hod','Yesod','Malkhut'];
const treeXY=[[0,1.83],[-.16,1.61],[.16,1.61],[-.24,1.32],[.24,1.32],[0,1.17],[-.17,.88],[.17,.88],[0,.73],[0,.15]];
const treePoints=treeNames.map((n,i)=>point('tree-'+i,n,treeXY[i][0],treeXY[i][1],.18,'#dfbe7b','A sefirah in a Keter-inclusive ten-sefirot scheme. This three-column display is a comparative diagram projected onto the body; traditions differ in enumeration and interpretation.',sources.tree));
const hdNames=['Head','Ajna','Throat','G / Identity','Heart / Ego','Spleen','Solar Plexus','Sacral','Root'];
const hdXY=[[0,1.87],[0,1.6],[0,1.44],[0,1.25],[-.15,1.17],[.19,1.02],[-.19,1.02],[0,.96],[0,.79]];
export const SPHERE_NAMES=['Life’s Work','Evolution','Radiance','Purpose','Attraction','IQ','EQ','SQ','Core / Vocation','Culture','Pearl'];
export const layers:MapLayer[]=[
 {id:'fields',name:'Neidan · Three dantian',note:'Three inner fields, with approximate landmarks from the Inner Atlas.',points:[...dantian,...landmarks],routes:[]},
 {id:'orbit',name:'Qigong · Small circulation',note:'Simplified rear ascent and front descent. This traces a traditional map, not a breathing cadence.',points:[],routes:[{id:'rear',color:'#efbd64',points:[[0,.805,0],[0,1.02,-.095],[0,1.32,-.11],[0,1.59,-.07],[0,1.704,-.015]]},{id:'front',color:'#69ded1',points:[[0,1.704,-.015],[0,1.6,.11],[0,1.44,.085],[0,1.29,.14],[0,.98,.12],[0,.805,0]]}]},
 {id:'sequence',name:'Attention · Five landmarks',note:'Perineum, belly, heart region, throat, and brow. Preserves the earlier Inner Atlas sequence as an illustrative path, separate from the traditional three-field map.',points:[point('sequence-throat','Throat',0,1.438,.075,'#87d5ff','A throat landmark in this attention sequence. It is not a thyroid or gland correspondence.',sources.neidan),point('sequence-brow','Brow',0,1.594,.115,'#b6b7ff','The brow is distinct from the internal upper field and the crown.',sources.neidan)],routes:[{id:'attention-path',color:'#b6b7ff',points:[[0,.805,.005],[0,.98,.035],[0,1.29,.035],[0,1.438,.075],[0,1.594,.115]]}]},
 {id:'chakras',name:'Yoga · Seven chakras',note:'One seven-center presentation; colors and placement are illustrative, not universal.',points:chakraNames.map((n,i)=>point('chakra-'+i,n,0,chakraY[i],.19,colors[i],'A center in this seven-chakra presentation. Compare position and symbolism without assuming identity with a dantian, gland, or nerve plexus.',sources.chakras,.032)),routes:[{id:'chakra-axis',color:'#b9a1ef',points:[[0,.81,.19],[0,1.76,.19]]}]},
 {id:'tree',name:'Kabbalah · Tree of Life',note:'Ten sefirot in a three-column scheme. Lines show the columns only, not a claimed canonical 22-path network.',points:treePoints,routes:[[0,5,8,9],[1,3,6],[2,4,7]].map((ids,i)=>({id:'pillar-'+i,color:'#dfbe7b',points:ids.map(j=>treePoints[j].position)}))},
 {id:'design',name:'Human Design · Nine centers',note:'A neutral nine-center template. Import your defined centers; empty centers do not mean “undefined.”',points:hdNames.map((n,i)=>point('hd-'+i,n,hdXY[i][0],hdXY[i][1],.23,'#a9c8d8','A Human Design center. No definition or channel activation has been calculated for you. Personal definition can be supplied from your existing chart.',sources.design,.028)),routes:[]},
 {id:'phases',name:'Chinese medicine · Five phases',note:'Traditional zang-phase associations, positioned approximately. These are not measures of organ function.',points:[['Wood · Liver',-.1,1.17,'#7dc88b'],['Fire · Heart',.04,1.31,'#ef8a72'],['Earth · Spleen',.12,1.16,'#e1c77c'],['Metal · Lung',-.1,1.4,'#c5d7df'],['Water · Kidney',.09,1.04,'#83bbee']].map((v,i)=>point('phase-'+i,String(v[0]),Number(v[1]),Number(v[2]),.24,String(v[3]),'A traditional five-phase association. This label refers to the traditional functional system and does not interpret biomedical laboratory values.',sources.phases)),routes:[]},
 {id:'alchemy',name:'Neidan · Essence, breath, spirit',note:'Jing, qi, and shen are alchemical categories, overlaid at the three fields.',points:dantian.map((p,i)=>({...p,id:'treasure-'+i,name:['精 · Jing','氣 · Qi','神 · Shen'][i],position:[p.position[0]-.12,p.position[1],.18] as [number,number,number],radius:.023})),routes:[]},
 {id:'keys',name:'Gene Keys · Personal spheres',note:'Enter the 11 sphere values from your profile. Their surrounding placement is a reading layout, not spiritual organ anatomy.',points:[],routes:[]},
 {id:'iching',name:'I Ching · 64 hexagrams',note:'King Wen numbering. The circle is a browsing arrangement, not a traditional body placement or astrological gate wheel.',points:Array.from({length:64},(_,i)=>{const a=i/64*Math.PI*2;return point('hex-'+(i+1),`${String.fromCodePoint(0x4dc0+i)} ${i+1}`,Math.sin(a)*.63,.98+Math.cos(a)*.9,-.12,i%2?'#d5b97b':'#9fcbbe',`Hexagram ${i+1} in King Wen order. Gene Key ${i+1} shares its number; no organ or medical correspondence is asserted.`,sources.iching,.012)}),routes:[]},
 {id:'astrology',name:'Astrology · Zodiac & placements',note:'A zodiac reference ring. Imported planetary longitudes place your chart markers; no natal calculation is implied.',points:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'].map((n,i)=>{const a=i/12*Math.PI*2;return point('zodiac-'+i,n,Math.sin(a)*.86,.98+Math.cos(a)*1.06,-.18,'#b8a5df',`${n} begins at ${i*30}° tropical zodiac longitude. The ring shows symbolic zodiac positions, not anatomical regions.`,'https://www.astro.com/astrowiki/en/Zodiac',.019)}),routes:[]},
];
