import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Download,Layers,RotateCcw,Upload} from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import AnatomyScene from './scene';
import Explorer from './explorer';
import {SYSTEMS,type Atlas,type SceneState,type SystemId,type View} from './anatomy';
import {layers,SPHERE_NAMES} from './spiritual-data';
import {type Overlay} from './overlay';
import {DEMO,parseImport,mergeRecords,normalizeRecord,type Measurement} from './health-data';
import {EMPTY_PROFILE,parseProfile,downloadJSON,type Profile} from './profile';
import {EDITION} from './edition';
const spiritual=EDITION==='spiritual';
const initial:SceneState={explode:0,visible:['skeletal','cardiac','respiratory','nervous','integumentary'],selected:[],isolate:false,view:'front',rotate:false,reset:0};
export default function Home(){
 const [atlas,setAtlas]=useState<Atlas|null>(null),[scene,setScene]=useState<SceneState>(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[explorer,setExplorer]=useState(false),[mobilePanel,setMobilePanel]=useState<'map'|'layers'|'details'>('map');
 const [enabled,setEnabled]=useState(['fields','orbit']),[selected,setSelected]=useState('lower'),[opacity,setOpacity]=useState(spiritual?.2:.85),[labels,setLabels]=useState(true),[search,setSearch]=useState('');
 const [measurements,setMeasurements]=useState<Measurement[]>([]),[metricKey,setMetricKey]=useState(''),[source,setSource]=useState('All sources'),[range,setRange]=useState('all'),[profile,setProfile]=useState<Profile>(EMPTY_PROFILE);
 useEffect(()=>{const abort=new AbortController();fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('The anatomical catalogue could not load.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});if(spiritual){try{const saved=localStorage.getItem('inner-atlas-profile-v1');if(saved)setProfile(parseProfile(saved));}catch{setNotice('The saved profile could not be read. Import a backup to restore it.');}}return()=>abort.abort();},[]);
 const metricOptions=useMemo(()=>[...new Map(measurements.map(r=>[JSON.stringify([r.metric,r.unit]),{key:JSON.stringify([r.metric,r.unit]),name:r.metric,unit:r.unit}])).values()], [measurements]);
 const currentMetric=metricOptions.find(m=>m.key===metricKey)??metricOptions[0];
 const availableSources=[...new Set(measurements.filter(r=>JSON.stringify([r.metric,r.unit])===currentMetric?.key).map(r=>r.source))];
 const series=useMemo(()=>{const all=measurements.filter(r=>JSON.stringify([r.metric,r.unit])===currentMetric?.key&&(source==='All sources'||r.source===source));const cutoff=range==='all'?-Infinity:Date.now()-Number(range)*86400000;return all.filter(r=>Date.parse(r.date)>=cutoff);},[measurements,currentMetric?.key,source,range]);
 const latest=series.at(-1),first=series[0];
 const activePoints=useMemo(()=>{
  if(!spiritual)return[];
  const points=layers.filter(l=>enabled.includes(l.id)).flatMap(l=>l.points).map(p=>p.id.startsWith('hd-')&&profile.definedCenters.includes(p.id)?{...p,color:'#efbd64',description:p.description+' Marked defined in your imported profile.'}:p);
  if(enabled.includes('keys'))SPHERE_NAMES.forEach((name,i)=>{const key=profile.geneKeys[name];if(!key)return;const angle=i/SPHERE_NAMES.length*Math.PI*2;points.push({id:'key-'+name,name:`${name} · ${key}`,position:[Math.sin(angle)*.48,1.02+Math.cos(angle)*.69,.25],color:'#e6b489',radius:.026,description:`Your entered Gene Key ${key} for ${name}. The location is a reading arrangement, not an anatomical claim.`,source:`https://genekeys.com/gene-key-${key}/`});});
  if(enabled.includes('astrology'))profile.planets.forEach((p,i)=>{const a=p.longitude/180*Math.PI;points.push({id:'planet-'+i,name:`${p.name} · ${p.longitude.toFixed(1)}°`,position:[Math.sin(a)*.75,.98+Math.cos(a)*.95,-.1],color:'#f0d28c',radius:.022,description:'An imported ecliptic longitude in the same zodiac system as your source chart. No birth-time calculation is performed here.'});});
  return points;
 },[enabled,profile]);
 const landmark=activePoints.find(p=>p.id===selected),selectedPart=atlas?.parts.find(p=>scene.selected.includes(p.id));
 const overlay:Overlay=useMemo(()=>({points:activePoints,routes:spiritual?layers.filter(l=>enabled.includes(l.id)).flatMap(l=>l.routes):[],selected,opacity,labels,dark:spiritual}),[activePoints,enabled,selected,opacity,labels]);
 function chooseLandmark(id:string){setSelected(id);setScene(s=>({...s,selected:[],isolate:false,explode:0}));setMobilePanel('details');}
 function chooseMetric(key:string){setMetricKey(key);setSource('All sources');const match=measurements.find(r=>JSON.stringify([r.metric,r.unit])===key);if(match&&match.system!=='general')setScene(s=>({...s,visible:['skeletal',match.system as SystemId],selected:[],isolate:false}));}
 function persistProfile(next:Profile){setProfile(next);try{localStorage.setItem('inner-atlas-profile-v1',JSON.stringify(next));setNotice('Profile saved in this browser. Export a backup to keep a separate copy.');}catch{setNotice('Browser storage is unavailable. Export your profile before closing.');}}
 async function importFile(file?:File){if(!file)return;setNotice('');try{if(file.size>80*1024*1024)throw Error('Use an export below 80 MB or split it into smaller files.');const result=parseImport(await file.text(),file.name);setMeasurements(old=>mergeRecords(old,result.records));setNotice(`Imported ${result.records.length.toLocaleString()} numeric records. ${result.skipped?`${result.skipped.toLocaleString()} nonnumeric Apple records were skipped. `:''}Matching metric, unit, timestamp, and source replace earlier rows.`);}catch(e){setNotice((e as Error).message);}}
 const bodyToggle=(id:SystemId)=>setScene(s=>({...s,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id],selected:[],isolate:false}));
 if(explorer)return <><Explorer/><Button className="return-atlas" onClick={()=>setExplorer(false)}><ArrowLeft/>Return to {spiritual?'Inner':'Health'} Atlas</Button></>;
 return <main className={`atlas-app ${spiritual?'spiritual':'health'}`}>
  <header className="atlas-header"><div className="atlas-brand"><span className="brand-symbol">{spiritual?'內':'H'}</span><div><p>{spiritual?'NEIDAN · SPIRITUAL ANATOMY':'HERMES · PERSONAL HEALTH'}</p><h1>{spiritual?'The Inner Atlas':'The Health Atlas'}</h1></div></div><Button variant="outline" onClick={()=>setExplorer(true)}><Layers size={17}/><span>Full anatomy explorer</span></Button></header>
  <nav className="mobile-tabs" aria-label="Workspace panels">{(['map','layers','details'] as const).map(p=><Button key={p} variant="ghost" aria-pressed={mobilePanel===p} onClick={()=>setMobilePanel(p)}>{p[0].toUpperCase()+p.slice(1)}</Button>)}</nav>
  <div className="atlas-workspace">
   <aside className={`atlas-sidebar ${mobilePanel==='layers'?'panel-active':''}`}>
    <div className="section-label">{spiritual?'TRADITIONS & LAYERS':'YOUR MEASUREMENTS'}</div>
    {spiritual?<><p className="panel-intro">Explore one map, or layer traditions around the same body.</p><div className="map-presets"><Button variant="outline" onClick={()=>setEnabled(['fields','orbit'])}>Neidan</Button><Button variant="outline" onClick={()=>setEnabled(['fields','chakras','tree'])}>Compare</Button><Button variant="ghost" onClick={()=>setEnabled([])}>Clear</Button></div>{layers.map(l=><div className="tradition" key={l.id}><label htmlFor={l.id}>{l.name}</label><Switch id={l.id} checked={enabled.includes(l.id)} onCheckedChange={checked=>setEnabled(old=>checked?[...old,l.id]:old.filter(x=>x!==l.id))}/>{enabled.includes(l.id)&&<p>{l.note}</p>}</div>)}</>:<><p className="panel-intro">Bring wearable readings, lab results, nutrition, and body measurements into one view.</p><label className="import-button"><Upload size={17}/>Import data<input type="file" accept=".json,.csv,.xml" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label><p className="muted">JSON, CSV, or Apple Health XML. Files are processed in this browser. No live connection is configured.</p><div className="map-presets"><Button variant="ghost" onClick={()=>{setMeasurements(DEMO);setMetricKey('');setSource('All sources');setNotice('Synthetic example data loaded. This is not your health history.');}}>Try example</Button><Button variant="ghost" onClick={()=>downloadJSON('health-import-example.json',{measurements:DEMO})}>Example format</Button></div><label className="field-label">Find a metric<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="HRV, glucose, weight…"/></label><div className="metric-list">{metricOptions.filter(m=>m.name.toLowerCase().includes(search.toLowerCase())).map(m=><Button variant="ghost" key={m.key} className={m.key===currentMetric?.key?'chosen':''} onClick={()=>chooseMetric(m.key)}><span>{m.name}</span><span>{m.unit}</span></Button>)}</div>{!measurements.length&&<p className="empty-note">Your atlas is ready for its first import.</p>}<details><summary>Import format</summary><p className="muted">CSV columns: metric, value, unit, date, source. An optional system column links a metric to anatomy. Use an ISO timestamp with timezone, or YYYY-MM-DD. Arbitrary numeric metrics are preserved. Apple XML imports quantity records; workouts, sleep stages, and clinical documents need conversion to numeric summaries.</p></details></>}
    <details className="anatomy-controls"><summary>Anatomical reference</summary>{SYSTEMS.map(s=><div className="reference-row" key={s.id}><label htmlFor={'system-'+s.id}>{s.name}</label><Switch id={'system-'+s.id} checked={scene.visible.includes(s.id)} onCheckedChange={()=>bodyToggle(s.id)}/></div>)}</details>
    <label className="field-label">Body opacity · {Math.round(opacity*100)}%<Slider min={5} max={100} step={5} value={[opacity*100]} onValueChange={v=>setOpacity((Array.isArray(v)?v[0]:v)/100)}/></label>
    {spiritual&&<div className="reference-row"><label htmlFor="point-labels">Point labels</label><Switch id="point-labels" checked={labels} onCheckedChange={setLabels}/></div>}
   </aside>
   <section className={`atlas-stage ${mobilePanel==='map'?'panel-active':''}`} aria-label="Interactive body map">
    {atlas&&<AnatomyScene atlas={atlas} state={scene} overlay={overlay} onLandmark={chooseLandmark} onSelect={id=>{setScene(s=>({...s,selected:[id]}));setSelected('');setMobilePanel('details');}} onProgress={setProgress} onError={setError}/>}
    <div className="stage-heading"><span>{spiritual?'CONTEMPLATIVE MAP · 3D':'ANATOMICAL REFERENCE · 3D'}</span><p>{spiritual?'Within the body.':currentMetric?.name??'A body of information.'}</p></div>
    {(progress<100||error)&&<div className="atlas-loading" role={error?'alert':'status'}>{error||`Loading anatomy · ${progress}%`}{error&&<Button onClick={()=>location.reload()}>Retry</Button>}</div>}
    <nav className="atlas-camera" aria-label="Body view">{(['front','side','back','three-quarter'] as View[]).map(v=><Button variant="ghost" key={v} aria-pressed={scene.view===v} onClick={()=>setScene(s=>({...s,view:v,reset:s.reset+1,isolate:false}))}>{v==='three-quarter'?'¾':v[0].toUpperCase()+v.slice(1)}</Button>)}<Button variant="ghost" aria-label="Reset body view" onClick={()=>setScene(s=>({...initial,visible:s.visible,reset:s.reset+1}))}><RotateCcw size={17}/></Button></nav>
    <p className="stage-caption">Drag to orbit · Scroll or pinch to zoom · Select to inspect</p>
   </section>
   <aside className={`atlas-inspector ${mobilePanel==='details'?'panel-active':''}`}>
    {spiritual?<><div className="section-label">LANDMARK & CONTEMPLATION</div><label className="field-label">Find a landmark<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Dantian, crown, Tiferet…"/></label><div className="landmark-list">{activePoints.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><Button variant="ghost" key={p.id} className={p.id===selected?'chosen':''} onClick={()=>chooseLandmark(p.id)}><i style={{background:p.color}}/>{p.name}</Button>)}</div>{landmark?<><p className="selected-kind">{landmark.kind??'PERSONAL PROFILE'}</p><h2>{landmark.name}</h2><p className="detail-copy">{landmark.description}</p>{landmark.source&&<a href={landmark.source} target="_blank" rel="noreferrer">Read source ↗</a>}<label className="field-label">Contemplation note<textarea key={selected} defaultValue={profile.notes[selected]??''} placeholder="What do you notice here?" onBlur={e=>{if(e.target.value!==(profile.notes[selected]??''))persistProfile({...profile,notes:{...profile.notes,[selected]:e.target.value}});}}/></label></>:<p className="detail-copy">Select a point on the body or in the list to explore its meaning.</p>}
     <details><summary>Your spiritual profile</summary><p className="muted">Enter existing chart values. This atlas does not calculate your birth chart. Notes and profile values stay in this browser.</p>{SPHERE_NAMES.map(n=><label className="sphere-entry" key={n}>{n}<input aria-label={`${n} Gene Key`} type="number" min={1} max={64} step={1} value={profile.geneKeys[n]??''} onChange={e=>{const keys={...profile.geneKeys};if(e.target.value==='')delete keys[n];else{const k=Number(e.target.value);if(!Number.isInteger(k)||k<1||k>64)return;keys[n]=k;}persistProfile({...profile,geneKeys:keys});}}/></label>)}<label className="import-button"><Upload size={16}/>Import profile<input type="file" accept=".json" onChange={async e=>{const input=e.currentTarget,f=input.files?.[0];if(f)try{persistProfile(parseProfile(await f.text()));}catch(err){setNotice((err as Error).message);}input.value='';}}/></label><Button variant="outline" onClick={()=>downloadJSON('inner-atlas-profile.json',profile)}><Download size={16}/>Export profile</Button><Button variant="ghost" onClick={()=>downloadJSON('profile-template.json',{geneKeys:{},definedCenters:[],planets:[],notes:{}})}>Download empty template</Button><p className="muted">Defined centers use hd-0 through hd-8 in the displayed nine-center order. Planet entries use name and longitude (0–359.999). Import values from one consistent zodiac system.</p></details>
     <p className="scope-note">These are traditional and symbolic maps over reference anatomy. Overlap invites comparison; it does not establish equivalence or measurable energy.</p>
    </>:<><div className="section-label">HEALTH HISTORY</div><h2>{currentMetric?.name??'Your health, in context.'}</h2>{currentMetric&&<><label className="field-label">Data source<select value={source} onChange={e=>setSource(e.target.value)}><option>All sources</option>{availableSources.map(s=><option key={s}>{s}</option>)}</select></label><label className="field-label">Time window<select value={range} onChange={e=>setRange(e.target.value)}><option value="all">All imported dates</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last year</option></select></label></>}{latest?<><div className="measurement-value">{latest.value.toLocaleString(undefined,{maximumFractionDigits:2})}<span>{latest.unit}</span></div><p className="muted">Latest recorded · {new Date(latest.date).toLocaleString()}<br/>{latest.source}</p>{first&&series.length>1&&<p className="delta">Change from first displayed reading: {(latest.value-first.value).toLocaleString(undefined,{maximumFractionDigits:2,signDisplay:'always'})} {latest.unit}</p>}<div className="trend-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={series.map(r=>({...r,time:Date.parse(r.date)}))} margin={{left:0,right:15,top:15,bottom:5}}><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={v=>new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'})} tick={{fontSize:12}} minTickGap={35}/><YAxis domain={['auto','auto']} width={45} tick={{fontSize:12}}/><Tooltip labelFormatter={v=>new Date(Number(v)).toLocaleString()} formatter={(v)=>[v,latest.unit]}/><Line type="linear" dataKey="value" stroke="#257e84" strokeWidth={2} dot={{r:3}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p className="muted">{series.length.toLocaleString()} readings. Multiple sources may measure differently.</p><details><summary>Reading history</summary><div className="reading-table"><table><thead><tr><th>Date</th><th>Value</th><th>Source</th></tr></thead><tbody>{series.slice().reverse().slice(0,100).map((r,i)=><tr key={i}><td>{new Date(r.date).toLocaleDateString()}</td><td>{r.value.toLocaleString(undefined,{maximumFractionDigits:2})} {r.unit}</td><td>{r.source}</td></tr>)}</tbody></table></div><p className="muted">Latest 100 shown. Export includes every imported reading.</p></details></>:<p className="detail-copy">{measurements.length?'No readings match this source and time window.':'Import your history to select a metric and explore its trend beside the relevant body system.'}</p>}
     <details><summary>Add a reading</summary><form className="reading-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;try{const data=Object.fromEntries(new FormData(form));const reading=normalizeRecord(data);setMeasurements(old=>mergeRecords(old,[reading]));setMetricKey(JSON.stringify([reading.metric,reading.unit]));setSource('All sources');setNotice('Reading added for this session. Export to save your data.');form.reset();}catch(err){setNotice((err as Error).message);}}}><label>Metric<input required name="metric" placeholder="ApoB"/></label><label>Value<input required name="value" type="number" step="any"/></label><label>Unit<input required name="unit" placeholder="mg/dL"/></label><label>Date<input required name="date" type="date"/></label><label>Source<input required name="source" placeholder="Lab name or device"/></label><Button type="submit">Add reading</Button></form></details>
     <div className="data-actions"><Button variant="outline" disabled={!measurements.length} onClick={()=>downloadJSON('health-atlas-data.json',{measurements})}><Download size={16}/>Export all data</Button><Button variant="ghost" disabled={!measurements.length} onClick={()=>{setMeasurements([]);setMetricKey('');setSource('All sources');setNotice('Session cleared. Your original files are unchanged.');}}>Clear session</Button></div><p className="scope-note">Measurements remain in this tab until you export or close it. The 3D body is reference anatomy, not a scan of you. Body-system associations organize readings; they do not diagnose organ health.</p>
    </>}
    {selectedPart&&<div className="selected-anatomy"><div className="section-label">SELECTED ANATOMY</div><h3>{selectedPart.name}</h3><p>{SYSTEMS.find(s=>s.id===selectedPart.system)?.description}</p><Button variant="outline" onClick={()=>setScene(s=>({...s,isolate:!s.isolate}))}>{scene.isolate?'Show body':'Isolate structure'}</Button></div>}
   </aside>
  </div>
  <footer className="atlas-footer"><span>Based on <a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">Ash’s Human Atlas</a> · <a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">BodyParts3D · CC BY 4.0</a></span><span>{spiritual?'Study · contemplation · embodied inquiry':'Observe · understand · keep your history'}</span></footer>
  {notice&&<div className="atlas-notice" role="status"><span>{notice}</span><Button variant="ghost" aria-label="Dismiss notice" onClick={()=>setNotice('')}>×</Button></div>}
 </main>;
}
