import type {SystemId} from './anatomy';
export type Measurement={metric:string;value:number;unit:string;date:string;source:string;system:SystemId|'general'};
const aliases:Record<string,string>={HKQuantityTypeIdentifierHeartRate:'Heart rate',HKQuantityTypeIdentifierRestingHeartRate:'Resting heart rate',HKQuantityTypeIdentifierHeartRateVariabilitySDNN:'HRV (SDNN)',HKQuantityTypeIdentifierBodyMass:'Weight',HKQuantityTypeIdentifierBodyFatPercentage:'Body fat',HKQuantityTypeIdentifierStepCount:'Steps',HKQuantityTypeIdentifierVO2Max:'VO₂ max',HKQuantityTypeIdentifierOxygenSaturation:'Oxygen saturation',HKQuantityTypeIdentifierBloodGlucose:'Blood glucose',HKQuantityTypeIdentifierRespiratoryRate:'Respiratory rate',HKQuantityTypeIdentifierBloodPressureSystolic:'Systolic blood pressure',HKQuantityTypeIdentifierBloodPressureDiastolic:'Diastolic blood pressure',HKQuantityTypeIdentifierActiveEnergyBurned:'Active energy',HKQuantityTypeIdentifierDietaryProtein:'Protein',HKQuantityTypeIdentifierLeanBodyMass:'Lean body mass'};
const systems=['skeletal','muscular','arterial','venous','nervous','digestive','respiratory','urinary','reproductive','lymphatic','endocrine','integumentary','connective','sensory','cardiac','general'];
export function inferSystem(metric:string):Measurement['system']{const m=metric.toLowerCase();if(/heart|hrv|blood pressure|cholesterol|ldl|hdl|apob/.test(m))return'cardiac';if(/oxygen|respirat|vo₂|vo2/.test(m))return'respiratory';if(/glucose|a1c|insulin|thyroid|tsh/.test(m))return'endocrine';if(/creatinine|egfr/.test(m))return'urinary';if(/sleep/.test(m))return'nervous';if(/muscle|lean body|steps|strength/.test(m))return'muscular';if(/protein|nutrition|calori|energy|alt|ast/.test(m))return'digestive';return'general';}
function csvRows(text:string){const out:string[][]=[];let row:string[]=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))out.push(row);row=[];cell='';}else cell+=c;}if(quote)throw new Error('CSV contains an unclosed quoted field.');row.push(cell);if(row.some(Boolean))out.push(row);return out;}
function normalizedDate(value:string){const date=/^\d{4}-\d\d-\d\d \d\d:\d\d:\d\d [+-]\d{4}$/.test(value)?value.replace(' ','T').replace(/ ([+-]\d\d)(\d\d)$/,'$1:$2'):value;if(!/^\d{4}-\d\d-\d\d(?:T.*(?:Z|[+-]\d\d:\d\d))?$/.test(date)||!Number.isFinite(Date.parse(date)))throw new Error('Use YYYY-MM-DD or an ISO timestamp with a timezone.');return new Date(date).toISOString();}
export function normalizeRecord(r:Record<string,unknown>):Measurement{
 let metric=String(r.metric??r.type??'').trim(),unit=String(r.unit??'').trim();if(!metric||r.value===null||r.value===undefined||String(r.value).trim()==='')throw new Error('Every row needs a metric and numeric value.');let value=Number(r.value);if(!Number.isFinite(value))throw new Error('Every value must be finite.');metric=aliases[metric]??metric;
 if(unit==='kg'&&/weight|body mass/i.test(metric)){value*=2.2046226218;unit='lb';}if(unit==='count/min'&&/heart rate/i.test(metric))unit='bpm';if(unit==='count/min'&&/respiratory/i.test(metric))unit='breaths/min';if(unit==='%'&&/body fat|oxygen saturation/i.test(metric)&&String(r.type??'').startsWith('HK'))value*=100;
 const date=normalizedDate(String(r.date??r.startDate??''));const system=String(r.system||inferSystem(metric));if(!systems.includes(system))throw new Error('Unknown anatomical system: '+system);
 return{metric,value,unit,date,source:String(r.source??r.sourceName??'Imported').trim()||'Imported',system:system as Measurement['system']};
}
export function parseImport(text:string,filename:string):{records:Measurement[];skipped:number}{
 let raw:Record<string,unknown>[];let skipped=0;
 if(filename.toLowerCase().endsWith('.xml')){const doc=new DOMParser().parseFromString(text,'text/xml');if(doc.querySelector('parsererror'))throw new Error('Apple Health XML could not be parsed.');raw=[];doc.querySelectorAll('Record').forEach(n=>{const r=Object.fromEntries(Array.from(n.attributes).map(a=>[a.name,a.value]));if(!String(r.type).startsWith('HKQuantityTypeIdentifier')){skipped++;return;}raw.push(r);});}
 else if(filename.toLowerCase().endsWith('.csv')){const rows=csvRows(text.replace(/^\uFEFF/,'')),head=rows.shift()?.map(v=>v.trim())??[];if(!head.includes('metric')||!head.includes('value')||!head.includes('date'))throw new Error('CSV needs metric,value,unit,date,source headers; system is optional.');raw=rows.map(row=>Object.fromEntries(head.map((h,i)=>[h,row[i]??''])));}
 else{const parsed=JSON.parse(text);raw=Array.isArray(parsed)?parsed:parsed.measurements;if(!Array.isArray(raw))throw new Error('JSON must be an array or contain a measurements array.');}
 const records=raw.map((r,i)=>{try{return normalizeRecord(r);}catch(e){throw new Error(`Record ${i+1}: ${(e as Error).message}`);}});if(!records.length)throw new Error('No numeric measurements were found.');return{records,skipped};
}
export function mergeRecords(a:Measurement[],b:Measurement[]){const map=new Map<string,Measurement>();for(const r of [...a,...b])map.set(JSON.stringify([r.metric,r.unit,r.date,r.source]),r);return [...map.values()].sort((x,y)=>x.date.localeCompare(y.date));}
export const DEMO:Measurement[]=[0,1,2,3,4,5,6].flatMap(i=>[{metric:'Resting heart rate',value:58+[2,1,3,0,1,-1,0][i],unit:'bpm',date:`2026-01-0${i+1}T08:00:00.000Z`,source:'Synthetic example',system:'cardiac' as const},{metric:'Weight',value:180-i*.15,unit:'lb',date:`2026-01-0${i+1}T08:00:00.000Z`,source:'Synthetic example',system:'general' as const}]);
